name: food_repository
description: Local package contain features with Edamam API
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
dependencies:
  freezed_annotation: ^2.4.1
  http: ^1.0.0
  json_annotation: ^4.8.1
  logger: ^1.4.0
